version: "3.8"

services:
    cache:
        image: redis:alpine
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
        restart: on-failure
        ports:
            - 6379

    ost-server:
        image: ojcastaneda/ost-server:latest
        restart: on-failure
        depends_on:
            - cache
        environment:
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_BUCKET=${AWS_BUCKET}
            - AWS_REGION=${AWS_REGION}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - BASE_USERNAME=${BASE_USERNAME}
            - BASE_PASSWORD=${BASE_PASSWORD}
            - DATABASE_URL=${DATABASE_URL}
            - OSU_API_CLIENT_ID=${OSU_API_CLIENT_ID}
            - OSU_API_CLIENT_SECRET=${OSU_API_CLIENT_SECRET}
            - REDIS_URL=redis://cache:6379
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
        ports:
            - 8080

    ost-bot:
        image: ojcastaneda/ost-bot:latest
        restart: on-failure
        depends_on:
            - ost-server
        environment:
            - API_URL=http://ost-server:8080
            - DISCORD_ID=1012092310776971344
            - DISCORD_TOKEN=${DISCORD_TOKEN}
            - DISCORD_URL=https://discord.com/invite/eNU3BE6bca
            - GITHUB_URL=https://github.com/ojcastaneda/osu-stamina-trainer
            - NODE_ENV=${NODE_ENV}
            - OSU_PASSWORD=${OSU_PASSWORD}
            - OSU_USERNAME=${OSU_USERNAME}
            - WEBSITE_URL=https://ost.sombrax79.org
        logging:
            driver: "json-file"
            options:
                max-size: "50m"

    ost-tasks:
        image: ojcastaneda/ost-tasks:latest
        restart: on-failure
        environment:
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_BUCKET=${AWS_BUCKET}
            - AWS_REGION=${AWS_REGION}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - DATABASE_URL=${DATABASE_URL}
            - OSU_API_CLIENT_ID=${OSU_API_CLIENT_ID}
            - OSU_API_CLIENT_SECRET=${OSU_API_CLIENT_SECRET}
            - PERIODIC=true
        logging:
            driver: "json-file"
            options:
                max-size: "50m"

    ost-website:
        image: ojcastaneda/ost-website:latest
        restart: on-failure
        depends_on:
            - ost-server
        environment:
            - NEXT_PUBLIC_API_URL=http://ost-server:8080
            - NEXT_PUBLIC_DISCORD_ID=1012092310776971344
            - NEXT_PUBLIC_DISCORD_URL=https://discord.com/invite/eNU3BE6bca
            - NEXT_PUBLIC_GITHUB_URL=https://github.com/ojcastaneda/osu-stamina-trainer
            - NEXT_PUBLIC_OSU_ID=6484647
            - NEXT_PUBLIC_PATREON_URL=https://www.patreon.com/osuStaminaTrainer
        container_name: ost-website
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
        ports:
            - 3000

    ost-routing:
        image: caddy:alpine
        restart: on-failure
        depends_on:
            - ost-server
            - ost-website
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
        ports:
        - "80:80"
        - "443:443"
        volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile
